name: ci

on: push


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: check system
      run: |
        lscpu

    - name: download data
      run: |
        mkdir -p data
        wget -q -c https://github.com/ren15/db_comparison/releases/download/0.0.1/binance-futures_trades_2023-01-01_BTCUSDT.csv.zst -O data/trades.csv.zst
        cd data
        zstd -d trades.csv.zst
        wc -l trades.csv
        ls -lah trades.csv

    - name: Install python dependencies
      run: |
        python3 -m pip install -U pip
        pip3 install pandas redis
        python3 scripts/read_trades.py

    - name: Run python-redis
      run: |
        bash solutions/redis/run.sh